# Generated by Django 3.2.5 on 2022-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_limit',
        ),
    ]
