# Generated by Django 3.2.5 on 2022-06-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_password_reset_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ot_token',
            new_name='is_ot_valid',
        ),
    ]
