# Generated by Django 3.2.5 on 2022-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_ot_token_user_is_ot_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ot_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='ot_token',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
